### ISSUE TITLE
Is the firmwares here better than the snapshots in the OpenWRT website?

### ISSUE THREAD

**Issue by felipecrs** [impulse/ac2100-openwrt-guide#15]
There are firmwares (snapshots) available in the OpenWRT wiki:

https://openwrt.org/toh/xiaomi/xiaomi_mi_router_ac2100#installation

I wonder which I should use, and if there are differences, what they are. I think this would fit better in the README. :)

**Comment by ecklf** [comment]
Repo files are scp07's build. No difference 👍
