### ISSUE TITLE
No connection received in telnet when running pppd-cve.py

### ISSUE THREAD

**Issue by jsaulalonso** [impulse/ac2100-openwrt-guide#16]
Hi,

I've following all tutorial steps, and update pppoe-simulator.py script with host_uniq fix, but when telnet is listening and I run pppd-cve.py script, no connection was received.

Could you help me?

**Comment by keys961** [comment]
same

**Comment by keys961** [comment]
Downgrade the firmware with version 1.0.14:  http://cdn.cnbj1.fds.api.mi-img.com/xiaoqiang/rom/rm2100/miwifi_rm2100_firmware_d517e_1.0.14.bin

Then follow all the tutorial steps without `host_uniq` fix.

You may try several times executing `pppd-cve.py` before receiving the connection from the router. (You can ignore the exception on missing the field `PPP over Ethernet` at line 17).

My env:
- macOS 11.2.3 (Intel)
- python 3.9.4
- scapy 2.4.5

**Comment by jsaulalonso** [comment]
It works! Than you @keys961
