### ISSUE TITLE
Why is the 5GHZ network not working?

### ISSUE THREAD

**Issue by p4c0ga** [impulse/ac2100-openwrt-guide#2]
Thank you very much for the work ...
I followed the manual and managed to install openwrt on my Mi AC2100 router, but ...
Why is the 5GHZ network not working? There's a solution? Any version that fixes it?

**Comment by ecklf** [comment]
Works perfectly fine for me. Did you enable the wireless interface in Luci?

**Comment by p4c0ga** [comment]
Not for me, 
when I try to configure in repeater mode, the 5Ghz  radio dawn and no get up more...
![Screenshot](https://user-images.githubusercontent.com/63509535/86511351-82125500-bdf8-11ea-938c-2f80e098d7a2.png)

**Comment by p4c0ga** [comment]
Is it possible to use the latest version of openwrt? Do you have any? Can I use the Readmi AC2100 with the same hardware?

**Comment by p4c0ga** [comment]
If I deactivate the associated network, the link does work
![Screenshot 2](https://user-images.githubusercontent.com/63509535/86511563-c0a90f00-bdfa-11ea-802d-0d7a5b61e761.png)

**Comment by ecklf** [comment]
Redmi builds should only be used for the white AC2100. There are available builds for both from @scp07 (on the forums). Please refer to the link in the repo.

It might be a bug, I personally don't use mt device in repeater mode.

Optionally try a clean flash if you came from an older image (I've had issues with systemupgrade before)

Use these commands if you are already on OpenWrt
```
mtd write kernel1.bin kernel
mtd -r write rootfs0.bin ubi
```

**Comment by p4c0ga** [comment]
Thanks, in advance
My installation is new and clear
I will try to search in the forum
Thanks again
