### ISSUE TITLE
Can't run busybox on Ubuntu20.4.1 LTS

### ISSUE THREAD

**Issue by youralmight** [impulse/ac2100-openwrt-guide#9]
If I run it in a normal user, it says
![image](https://user-images.githubusercontent.com/42952005/99833384-dbf39b80-2b9c-11eb-94d6-dd9cbdee8606.png)

Then I run it with root, it says
![image](https://user-images.githubusercontent.com/42952005/99833423-ed3ca800-2b9c-11eb-926d-1cbce75f98d6.png)

I checked the size of the busybox file, it should be right.
What version of Ubuntu should I use?

**Comment by ecklf** [comment]
https://github.com/impulse/ac2100-openwrt-guide/issues/3#issuecomment-657778389

**Comment by youralmight** [comment]
Oh, I got it. You should input those commands where you run netcat instead of in a new terminal
